name: Deployment

on:
  push:
    tags:
      - "20.*"
      - "21.*"
      - "22.*"
      - "23.*"
      - "24.*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm test
    - name: Update extension’s meta
      run: |
        export VER=$(echo "$GITHUB_REF" | sed -e 's/refs\/tags\///')
        echo https://github.com/$GITHUB_REPOSITORY/tree/$VER > dist/SOURCE_URL
        npm run version
    - uses: actions/upload-artifact@v1
      with:
        name: built-extension
        path: dist

  deploy-to-chrome:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: built-extension
        path: dist
    - run: cd dist && npx chrome-webstore-upload-cli upload --auto-publish
      env:
        EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
